"""
Turn copper masks into a FastHenry model, run the solver, read back L(f).

Meshing model ("uniform Manhattan PEEC"):
  * Each filled cell of a CopperMask becomes a FastHenry node at the cell centre,
    at the layer's z height.
  * Orthogonally-adjacent filled cells are joined by a FastHenry segment (E line)
    of width = pitch, height = copper thickness. The resulting grid of bars is a
    discretised sheet; FastHenry then computes the full partial-inductance matrix
    among all bars, including mutual coupling and (via nwinc/nhinc filaments)
    skin/proximity effect.
  * Forward and return conductors live on different layers (different z). They are
    tied together by vertical VIA segments at the drilled via locations that land
    on both conductors -- this is the "far end / load" that closes the loop.
  * The measurement PORT is a `.external` between the forward node nearest
    terminal A and the return node nearest terminal B.

L(f) = Im(Z_port(f)) / (2*pi*f), with Z read from FastHenry's Zc.mat.

This module only *writes* and *parses*; it shells out to a `fasthenry` binary
whose path is configurable. Everything it writes goes under the caller-provided
output directory (kept inside tools/inductance/).
"""

from __future__ import annotations

import json
import math
import os
import re
import shutil
import subprocess
import time
from dataclasses import dataclass

import numpy as np

from geometry import CopperMask

MU0 = 4e-7 * math.pi
SIGMA_CU_SI = 5.8e7          # S/m, annealed copper


@dataclass
class Conductor:
    """One meshed conductor: its mask plus physical placement."""
    mask: CopperMask
    z: float                 # mm, height of the copper layer (segment centre plane)
    thickness: float         # mm, copper thickness
    tag: str                 # 'f' (forward) or 'r' (return); used in node names


@dataclass
class Via:
    x: float
    y: float
    diameter: float          # mm


def _cells(mask: CopperMask):
    """Yield (id, j, i, xc, yc) for each filled cell, id is a stable index."""
    js, is_ = np.nonzero(mask.mask)
    out = {}
    for k in range(len(js)):
        j, i = int(js[k]), int(is_[k])
        out[(j, i)] = k
    return js, is_, out


def build_inp(forward: Conductor,
              ret: Conductor,
              vias: list[Via],
              term_a: tuple[float, float],
              term_b: tuple[float, float],
              fmin: float, fmax: float, ndec: float,
              units: str = "mm",
              skin_ref_freq: float | None = None,
              max_filaments: int = 5,
              shorts: list[tuple[float, float]] | None = None) -> tuple[str, dict]:
    """
    Build a FastHenry input deck. Returns (text, meta) where meta records the
    segment count and the chosen port nodes for reporting.

    Loop closure happens by one of two mechanisms, depending on the physical case:
      * `vias`   : vertical copper segments tying forward<->return. Correct when
                   forward and return are the SAME net stitched across two layers.
      * `shorts` : ideal node merges (`.equiv`) between the nearest forward and
                   return nodes at each (x,y). Correct for a power->load->ground
                   loop, where the loop closes through an external component (the
                   load), NOT through a copper via. Place one short at the load.
    """
    lines: list[str] = []
    lines.append("* Auto-generated by gerber_inductance.py")
    lines.append("* Loop inductance: forward net + explicit return, swept L(f).")
    lines.append(f".units {units}")

    sigma = SIGMA_CU_SI / 1000.0 if units == "mm" else SIGMA_CU_SI  # S/mm vs S/m
    lines.append("")

    seg_count = 0
    node_count = 0
    port_nodes: dict[str, str] = {}

    # skin-depth-driven filament counts at the top of the sweep
    fref = skin_ref_freq if skin_ref_freq else fmax
    delta = _skin_depth(fref) * (1000.0 if units == "mm" else 1.0)   # in units

    for cond in (forward, ret):
        node_js, node_is, cell_id = _cells(cond.mask)
        p = cond.mask.pitch
        nhinc = _winc(cond.thickness, delta, max_filaments)
        nwinc = _winc(p, delta, max_filaments)

        lines.append(f"* ---- conductor '{cond.tag}'  z={cond.z} t={cond.thickness} "
                     f"cells={len(node_js)} ----")
        # nodes
        for k in range(len(node_js)):
            j, i = int(node_js[k]), int(node_is[k])
            xc, yc = cond.mask.cell_center(j, i)
            lines.append(f"N{cond.tag}{k} x={xc:.4f} y={yc:.4f} z={cond.z:.4f}")
            node_count += 1
        # segments: east and north neighbours
        cs = f"w={p:.4f} h={cond.thickness:.4f} sigma={sigma:.6g} "\
             f"nwinc={nwinc} nhinc={nhinc}"
        for (j, i), k in cell_id.items():
            for (dj, di) in ((0, 1), (1, 0)):
                nb = cell_id.get((j + dj, i + di))
                if nb is not None:
                    lines.append(f"E{cond.tag}{seg_count} N{cond.tag}{k} "
                                 f"N{cond.tag}{nb} {cs}")
                    seg_count += 1
        cond._cell_id = cell_id  # type: ignore[attr-defined]

    # ---- vias: vertical segments tying forward<->return ---------------------
    via_seg = 0
    fwd_cells = forward._cell_id            # type: ignore[attr-defined]
    ret_cells = ret._cell_id               # type: ignore[attr-defined]
    for v in vias:
        fj, fi = forward.mask.world_to_cell(v.x, v.y)
        rj, ri = ret.mask.world_to_cell(v.x, v.y)
        fk = fwd_cells.get((fj, fi))
        rk = ret_cells.get((rj, ri))
        if fk is None or rk is None:
            continue
        d = max(v.diameter, forward.mask.pitch)
        lines.append(f"Ev{via_seg} Nf{fk} Nr{rk} w={d:.4f} h={d:.4f} "
                     f"sigma={sigma:.6g} nwinc=1 nhinc=1")
        via_seg += 1

    # ---- port ---------------------------------------------------------------
    ka = _nearest_cell_id(forward, term_a)
    kb = _nearest_cell_id(ret, term_b)
    if ka is None or kb is None:
        raise ValueError("Could not place port: terminal A must land on the "
                         "forward net and terminal B on the return net.")
    na, nb = f"Nf{ka}", f"Nr{kb}"
    port_nodes = {"A": na, "B": nb}

    # ---- ideal-short closures (.equiv) at load/source ends ------------------
    n_short = 0
    for (sx, sy) in (shorts or []):
        fj, fi = forward.mask.world_to_cell(sx, sy)
        sk = fwd_cells.get((fj, fi))
        rj, ri = ret.mask.world_to_cell(sx, sy)
        rk = ret_cells.get((rj, ri))
        if sk is None:
            sk = _nearest_cell_id(forward, (sx, sy))
        if rk is None:
            rk = _nearest_cell_id(ret, (sx, sy))
        if sk is not None and rk is not None:
            lines.append(f".equiv Nf{sk} Nr{rk}")
            n_short += 1

    lines.append("")
    lines.append(f".external {na} {nb}")
    lines.append(f".freq fmin={fmin:.6g} fmax={fmax:.6g} ndec={ndec:.6g}")
    lines.append(".end")

    meta = {
        "segments": seg_count,
        "via_segments": via_seg,
        "shorts": n_short,
        "nodes": node_count,
        "port_nodes": port_nodes,
        "skin_depth_mm": delta,
    }
    return "\n".join(lines) + "\n", meta


def _nearest_cell_id(cond: Conductor, pt: tuple[float, float]):
    cell_id = cond._cell_id            # type: ignore[attr-defined]
    j0, i0 = cond.mask.world_to_cell(*pt)
    if (j0, i0) in cell_id:
        return cell_id[(j0, i0)]
    best, bestd = None, 1e18
    for (j, i), k in cell_id.items():
        d = (j - j0) ** 2 + (i - i0) ** 2
        if d < bestd:
            bestd, best = d, k
    return best


def _skin_depth(freq: float) -> float:
    """Copper skin depth (metres) at `freq` Hz. DC -> large but capped."""
    if freq <= 0:
        return 1.0
    return math.sqrt(2.0 / (2 * math.pi * freq * MU0 * SIGMA_CU_SI))


def _winc(dim: float, delta: float, cap: int) -> int:
    """Filament count to resolve skin effect across `dim` given skin depth delta."""
    if delta <= 0:
        return 1
    n = int(math.ceil(dim / max(delta, 1e-9)))
    return max(1, min(cap, n))


# ----------------------------------------------------------------------------
# Run + parse
# ----------------------------------------------------------------------------

def find_fasthenry(explicit: str | None) -> str | None:
    """Resolve a command-line fasthenry binary: explicit path, $FASTHENRY, or PATH."""
    for cand in (explicit, os.environ.get("FASTHENRY")):
        if cand and os.path.isfile(cand):
            return cand
    return shutil.which("fasthenry")


def find_solver(explicit: str | None) -> tuple[str | None, str | None]:
    """
    Locate a usable FastHenry. Returns (mode, target):
      ('cli', '/path/fasthenry')      -- a command-line binary (writes Zc.mat)
      ('com', 'FastHenry2.Document')  -- the FastFieldSolvers COM server (Windows)
      (None, None)                    -- nothing found
    The Windows FastFieldSolvers install ships only the GUI exe, which is also a
    COM automation server; we drive it headless via run_fasthenry_com.ps1.
    """
    cli = find_fasthenry(explicit)
    if cli:
        return ("cli", cli)
    # COM server? Look for its registered ProgID.
    try:
        r = subprocess.run(["reg", "query", r"HKCR\FastHenry2.Document"],
                           capture_output=True, text=True)
        if r.returncode == 0:
            return ("com", "FastHenry2.Document")
    except Exception:                            # noqa: BLE001
        pass
    return (None, None)


def run_via_com(inp_path: str, workdir: str,
                progid: str = "FastHenry2.Document",
                ps_script: str | None = None,
                max_retries: int = 4) -> list[tuple[float, float, float]]:
    """
    Solve a single deck `inp_path` via the FastHenry2 COM server and return
    [(freq_Hz, R_ohm, L_henry), ...] for the frequencies in the deck's `.freq`
    line. R is NaN if the server doesn't expose it.

    The COM server occasionally returns an empty result, and once an instance is
    wedged, recreating it in the SAME PowerShell process does not recover. So each
    retry is a FRESH PowerShell process (fresh COM apartment). The .ps1 writes the
    JSON only on a non-empty result; absence of the file means "retry".
    """
    here = os.path.dirname(os.path.abspath(__file__))
    ps_script = ps_script or os.path.join(here, "run_fasthenry_com.ps1")
    out_json = os.path.join(workdir, "fasthenry_com.json")
    inp_abs = os.path.abspath(inp_path)
    cmd = ["powershell", "-NoProfile", "-ExecutionPolicy", "Bypass",
           "-File", ps_script, "-Inp", inp_abs, "-Out", out_json, "-ProgId", progid]

    last = ""
    for attempt in range(1, max_retries + 1):
        if os.path.exists(out_json):
            os.remove(out_json)
        proc = subprocess.run(cmd, capture_output=True, text=True)
        last = proc.stdout + "\n" + proc.stderr
        if proc.returncode != 0:
            raise RuntimeError("FastHenry COM run failed (hard error):\n" + last)
        if os.path.isfile(out_json):
            break                                    # success: JSON written
        time.sleep(0.8)                              # empty result -> fresh-process retry
    else:
        raise RuntimeError(f"FastHenry returned an empty result after {max_retries} "
                           f"fresh-process attempts. Try a coarser mesh_pitch_mm and "
                           f"verify the closure.\n" + last)

    with open(out_json, encoding="utf-8-sig") as fh:
        data = json.load(fh)
    if isinstance(data, dict):
        data = [data]
    rows = []
    for d in data:
        R = d.get("R")
        rows.append((float(d["f"]), float(R) if R is not None else float("nan"),
                     float(d["L"])))
    if not rows:
        raise RuntimeError("FastHenry COM run returned no frequency points.\n" + last)
    rows.sort(key=lambda r: r[0])
    return rows


def sweep_frequencies(fmin: float, fmax: float, ndec: float) -> list[float]:
    """FastHenry's logarithmic sweep points: ndec per decade, fmin..fmax inclusive."""
    if fmax <= fmin:
        return [fmin]
    n = int(round(math.log10(fmax / fmin) * ndec))
    return [fmin * (10.0 ** (i / ndec)) for i in range(n + 1)]


def _rewrite_freq(deck_text: str, f: float) -> str:
    """Return the deck with its `.freq` line replaced by a single point at f."""
    out = []
    for line in deck_text.splitlines():
        if line.strip().lower().startswith(".freq"):
            out.append(f".freq fmin={f:.6g} fmax={f:.6g} ndec=1")
        else:
            out.append(line)
    return "\n".join(out) + "\n"


def run_sweep_per_freq(inp_path: str, freqs: list[float], workdir: str,
                       progid: str = "FastHenry2.Document",
                       progress=None) -> list[tuple[float, float, float]]:
    """
    Solve a frequency sweep as a SEQUENCE of single-frequency decks.

    The FastHenry2 COM server is unreliable on multi-frequency decks (returns an
    empty result for some meshes) but solves single-frequency decks dependably.
    So we rewrite the deck's `.freq` line per point and solve each separately,
    assembling L(f) ourselves. Slower (no shared setup) but robust.
    """
    with open(inp_path) as fh:
        deck = fh.read()
    rows = []
    for k, f in enumerate(freqs):
        single = _rewrite_freq(deck, f)
        tmp = os.path.join(workdir, "loop_pt.inp")
        with open(tmp, "w") as out:
            out.write(single)
        r = run_via_com(tmp, workdir, progid=progid)
        rows.extend(r)
        if progress:
            progress(k + 1, len(freqs), r[0])
    rows.sort(key=lambda r: r[0])
    return rows


def run_fasthenry(inp_path: str, binary: str, workdir: str) -> str:
    """Run fasthenry on inp_path inside workdir; return path to Zc.mat."""
    binary = os.path.abspath(binary)
    rel = os.path.relpath(os.path.abspath(inp_path), workdir)
    proc = subprocess.run([binary, rel], cwd=workdir,
                          capture_output=True, text=True)
    if proc.returncode != 0:
        raise RuntimeError(f"fasthenry failed (rc={proc.returncode}):\n"
                           f"{proc.stdout}\n{proc.stderr}")
    zc = os.path.join(workdir, "Zc.mat")
    if not os.path.isfile(zc):
        raise RuntimeError("fasthenry did not produce Zc.mat:\n" + proc.stdout)
    return zc


def parse_zc(zc_path: str) -> list[tuple[float, complex]]:
    """
    Parse FastHenry Zc.mat into [(freq_Hz, Z_ohm), ...] for a 1-port deck.
    Zc.mat blocks look like:
        Impedance matrix for frequency = 1e+06  1 x 1
        <real> <imag>
    """
    out: list[tuple[float, complex]] = []
    freq = None
    with open(zc_path) as fh:
        for line in fh:
            s = line.strip()
            mf = re.search(r"frequency\s*=\s*([0-9.eE+-]+)", s)
            if mf:
                freq = float(mf.group(1))
                continue
            if freq is not None:
                m = re.findall(r"[-+0-9.eE]+", s)
                if len(m) >= 2:
                    z = complex(float(m[0]), float(m[1]))
                    out.append((freq, z))
                    freq = None
    return out


def inductance_table(zc: list[tuple[float, complex]]) -> list[tuple[float, float, float]]:
    """Map [(f,Z)] -> [(f, R_ohm, L_henry)]; L=Im(Z)/(2*pi*f)."""
    rows = []
    for f, z in zc:
        L = z.imag / (2 * math.pi * f) if f > 0 else float("nan")
        rows.append((f, z.real, L))
    return rows
