// drive_siso_coeffs.h — GENERATED by controller_design_MIMO/synthesize_drive_siso.py
// DO NOT EDIT BY HAND.  Regenerate after bench calibration (mimo_system_model.md §9).
//
// *** NOT WIRED INTO ANY FIRMWARE BUILD. ***  This is the Phase-3 DECENTRALIZED
// BASELINE drive controller for the MIMO study (controller_design_MIMO/), emitted in
// the shipped share-controller header format purely so the Teensy implementation cost
// is quantified on equal terms.  No firmware source includes this file.
//
// SISO Youla-H velocity controller for the SC001 drive channel:
//   Gc(z) = R(z) + kI*Ts/2*(z+1)/(z-1),  e = v_ref - v [m/s]  ->  i_cmd [A]
// H-inf mixed sensitivity (gamma = 13.6858) + Youla-H DC rescale (T(0) = 1 exact),
// Tustin at Ts = 2.0 ms (500 Hz motor channel; VESC UART frame floor).
// R(z) is 2 DF2T biquad section(s); the integrator is kept separate to match the
// shipped share-controller header layout byte for byte.
//
// *** ANTI-WINDUP WARNING (differs from share_controller.h) ***
// The shipped share controller de-winds by back-calculating ONLY the integrator.  That
// is NOT sufficient here: the non-integral branch R has a low-frequency gain of
// 367.7 A/(m/s), so against the +-20 A clamp the biquad cascade alone saturates for
// |e| > 54.4 mm/s and its lag states wind up independently of the integrator.
// Measured on the 0->2 m/s step: integrator-only AW leaves a -0.10 m/s standing error
// and a 6.3 mm/s limit cycle.
// RE-CHECKED at the revised +-20 A clamp (2026-08-04): raising the clamp 4x raises
// e_sat 4x too, so integrator-only AW is now CLEAN for steps up to ~0.2 m/s (final
// error < 1e-4 m/s, no limit cycle) and only breaks from ~0.5 m/s upward.  It still
// FAILS the 0->2 m/s gate, so the Hanus form is still REQUIRED for this baseline --
// but the failure boundary has moved from small-signal into large-transient territory.
// A correct implementation must condition the FULL
// controller state (Hanus self-conditioned form, used in the synthesis sims):
//     u_unsat = Cd x + Dd e ;  u = clamp(u_unsat) ;
//     x[k+1]  = (Ad - Bd*Cd/Dd) x + Bd*u/Dd            (Dd = 1.035961461e+00)
// i.e. this baseline costs a 5-state state-space realization on the Teensy, not a
// biquad cascade.  Recorded as a Phase-6 "Teensy implementation cost" datapoint.
#pragma once

#define DRIVE_CTRL_TS_US   2000      // controller update period, microseconds
#define DRIVE_CTRL_NSOS    2
static const float DRIVE_CTRL_KI = 5.053406699e+01f;   // integrator gain (continuous kI, Tustin in code)
static const float DRIVE_CTRL_I_MIN = -2.000000000e+01f;   // A, motor current clamp (regen rail)
static const float DRIVE_CTRL_I_MAX = 2.000000000e+01f;    // A, motor current clamp (drive rail)

// biquad sections: b0 b1 b2 a1 a2 (a0 = 1)
static const float DRIVE_CTRL_SOS[DRIVE_CTRL_NSOS][5] = {
    { 9.854273937e-01f, 1.532252710e+00f, 5.468253164e-01f, -1.434728893e+00f, 5.070941944e-01f },
    { 1.000000000e+00f, -1.982496239e+00f, 9.825055474e-01f, -1.997498169e+00f, 9.974992414e-01f },
};
