// drive_siso_coeffs.h — GENERATED by controller_design_MIMO/synthesize_drive_siso.py
// DO NOT EDIT BY HAND.  Regenerate after bench calibration (mimo_system_model.md §9).
//
// *** STUDY COPY — NOT INCLUDED BY ANY FIRMWARE SOURCE. ***  This is the Phase-3
// DECENTRALIZED BASELINE drive controller for the MIMO study (controller_design_MIMO/),
// emitted in the shipped share-controller header format so the Teensy implementation
// cost is quantified on equal terms.
// The FIRMWARE copy of these same coefficients EXISTS as of fw v10 and is written by
// this same script to teensy_controller/drive_controller_coeffs.h; the runtime that
// consumes it is teensy_controller/drive_controller.h (Hanus form, double states),
// enabled by USE_YOULA_DRIVE_CONTROLLER.  Both files are emitted from one code path —
// do not hand-edit either.
//
// SISO Youla-H velocity controller for the SC001 drive channel:
//   Gc(z) = R(z) + kI*Ts/2*(z+1)/(z-1),  e = v_ref - v [m/s]  ->  i_cmd [A]
// H-inf mixed sensitivity (gamma = 27.8402) + Youla-H DC rescale (T(0) = 1 exact),
// Tustin at Ts = 2.0 ms (500 Hz motor channel; VESC UART frame floor).
// R(z) is 2 DF2T biquad section(s); the integrator is kept separate to match the
// shipped share-controller header layout byte for byte.
//
// *** ANTI-WINDUP WARNING (differs from share_controller.h) ***
// The shipped share controller de-winds by back-calculating ONLY the integrator.  That
// is NOT sufficient here: the non-integral branch R has a low-frequency gain of
// 459.1 A/(m/s), so against the +-12 A clamp the biquad cascade alone saturates for
// |e| > 26.1 mm/s and its lag states wind up independently of the integrator.
// Measured on the 0->2 m/s step: integrator-only AW leaves a -0.27 m/s standing error
// and a 20.9 mm/s limit cycle.
// RE-CHECKED at the firmware's +-12 A clamp (2026-08-15 operator decision) on the
// re-identified plant (2026-08-16 calibration): e_sat scales with the clamp, so it must be
// re-answered on every clamp change.  Integrator-only AW is CLEAN for steps up to
// ~0.1 m/s (final error < 1e-4 m/s, no limit cycle) and breaks from ~0.2 m/s upward.
// It still FAILS the 0->2 m/s gate, so the Hanus form remains REQUIRED for this baseline.
// A correct implementation must condition the FULL
// controller state (Hanus self-conditioned form, used in the synthesis sims):
//     u_unsat = Cd x + Dd e ;  u = clamp(u_unsat) ;
//     x[k+1]  = (Ad - Bd*Cd/Dd) x + Bd*u/Dd            (Dd = 1.704741304e+00)
// i.e. this baseline costs a 5-state state-space realization on the Teensy, not a
// biquad cascade.  Recorded as a Phase-6 "Teensy implementation cost" datapoint.
// The realization is emitted below (DRIVE_CTRL_AD/BD/CD/DD/AC); replay reference vectors
// for a firmware implementation are in figures/drive_siso_replay.csv.
#pragma once

#define DRIVE_CTRL_TS_US   2000      // controller update period, microseconds
#define DRIVE_CTRL_NSOS    2
static const float DRIVE_CTRL_KI = 7.904359361e+01f;   // integrator gain (continuous kI, Tustin in code)
// constexpr (not plain const) so the firmware can static_assert these against its own
// MOTOR_I_CMD_MAX: a namespace-scope `const float` is NOT a constant expression in C++17, so
// the clamp-pairing guard would not compile against it.  Same float32 values either way.
static constexpr float DRIVE_CTRL_I_MIN = -1.200000000e+01f;   // A, motor current clamp (regen rail)
static constexpr float DRIVE_CTRL_I_MAX = 1.200000000e+01f;    // A, motor current clamp (drive rail)

// biquad sections: b0 b1 b2 a1 a2 (a0 = 1)
static const float DRIVE_CTRL_SOS[DRIVE_CTRL_NSOS][5] = {
    { 1.625697710e+00f, 2.672945704e+00f, 1.047247993e+00f, -1.484867435e+00f, 5.562178644e-01f },
    { 1.000000000e+00f, -1.157898897e+00f, 1.698352436e-01f, -1.157917491e+00f, 1.598655417e-01f },
};

// ── Hanus self-conditioned state-space realization ──────────────────────────
// This is the FULL controller Gc(z) = R(z) + kI*Ts/2*(z+1)/(z-1) realized as one
// 5-state discrete system, NOT a second copy of the biquads above.  DRIVE_CTRL_SOS is
// retained only for the unsaturated-equivalence test; the state-space form below is the
// one to implement, because it is the only one that de-winds correctly (see the
// anti-windup warning at the top of this file).
//
// Dimensions: n = 5 states, 1 input (velocity error e [m/s]), 1 output (i_cmd [A]).
//   AD is n x n, BD is n x 1, CD is 1 x n, DD is scalar, AC = AD - BD*CD/DD is n x n.
// All arrays are ROW-MAJOR.
//
// Update law, once per DRIVE_CTRL_TS_US, with e = v_ref - v_actual [m/s]:
//   u_unsat = sum_j CD[0][j]*x[j] + DD*e
//   u       = clamp(u_unsat, DRIVE_CTRL_I_MIN, DRIVE_CTRL_I_MAX)     -> i_cmd [A]
//   x_next[i] = sum_j AC[i][j]*x[j] + BD[i][0]*(u/DD)
//   x <- x_next
// Note the conditioning: the state update is driven by the CLAMPED u, not by e.  While
// unsaturated this is algebraically identical to x_next = AD x + BD e (that identity is
// what makes AD useful as a cross-check); once clamped it is what prevents windup.
// Replay vectors for both regimes: figures/drive_siso_replay.csv.
//
// NUMERICAL CAUTION — read before implementing.
// This realization contains an exact integrator (an AD eigenvalue at 1) and a second mode
// at ~0.9999, alongside CD entries of order 50.  Perturbations are INTEGRATED, not damped,
// so coefficient precision and arithmetic precision both matter more than usual here.
//   * COEFFICIENTS.  The values below are the exact float32 roundings of the synthesis
//     matrices, and figures/drive_siso_replay.csv was generated from these same rounded
//     values.  Header, replay vectors and a compiled constant table therefore hold
//     bit-identical coefficients.  (Emitting float64 text instead put the reference
//     vectors 1.7e-2 A away from anything this header can reproduce.)  AC is derived from
//     the rounded AD/BD/CD/DD and then rounded, so AC == AD - BD*CD/DD holds to
//     1.7e-06 — a float32 rounding of AC's largest entry, not a compounding error.
//   * ARITHMETIC.  The replay vectors assume a float64 (double) state recursion.  Running
//     the recursion in float32 costs a further ~1e-2 A on the saturated regen episode —
//     measured, not estimated (validate_drive_siso.py check 4).  The divergence appears
//     at rail RELEASE rather than by slow accumulation, so it is not bounded by shortening
//     the run.  A float32 state recursion is NOT adequate for this controller; use double
//     (or fixed point with equivalent headroom).
// Replay comparisons should be toleranced on the OUTPUT (i_cmd), never on the individual
// states — and the two episodes need DIFFERENT tolerances:
//     'small' (unsaturated) : 1e-04 A or tighter.  Clean test of the linear recursion
//                             (measured on the firmware arithmetic path: 2.38e-04 mA).
//     'regen' (saturated)   : 180 mA.  During the saturated transient this controller
//                             dithers across the +-12 A clamp boundary (74 clamp-state
//                             transitions in the emitted vectors, closest boundary
//                             approach 255.9 uA), so one flipped decision — which any
//                             perturbation can cause — is worth ~8 A of state drive.
//                             Measured worst sensitivity 86.27 mA
//                             (scalar-order arithmetic (firmware path));
//                             the shipped tolerance is 2x that, rounded up.  A tighter
//                             tolerance fails correct implementations.  NOTE the largest
//                             perturbation is the ARITHMETIC ORDER of the dot products
//                             (scalar C loop vs BLAS), not stimulus precision.
// These tolerances are MEASURED per synthesis run and shipped machine-readably as
// DRIVE_REPLAY_<EPISODE>_TOL_A in controller_design_MIMO/drive_replay_vectors.h — read
// those macros, do not copy the numbers above into a test.
// Full detail in the figures/drive_siso_replay.csv header.
#define DRIVE_CTRL_NSTATES 5
static const float DRIVE_CTRL_DD = 1.70474135875701904e+00f;   // direct feedthrough, A per (m/s)

// AD [5][5] — unconditioned state matrix (cross-check only)
static const float DRIVE_CTRL_AD[5][5] = {
    { 1.00000000000000000e+00f, 0.00000000000000000e+00f, 0.00000000000000000e+00f, 0.00000000000000000e+00f, 0.00000000000000000e+00f },
    { 0.00000000000000000e+00f, 9.95481312274932861e-01f, -1.53927719220519066e-02f, 1.40468608587980270e-02f, 3.71024390915408731e-04f },
    { 0.00000000000000000e+00f, -1.53927728533744812e-02f, 9.00439560413360596e-01f, 1.70944705605506897e-01f, 3.17541928961873055e-03f },
    { 0.00000000000000000e+00f, -1.40468608587980270e-02f, -1.70944720506668091e-01f, 5.84849894046783447e-01f, -2.95379124581813812e-02f },
    { 0.00000000000000000e+00f, -3.72167385648936033e-04f, -3.18511575460433960e-03f, -2.96297762542963028e-02f, 1.62014141678810120e-01f },
};

// BD [5][1] — input matrix
static const float DRIVE_CTRL_BD[5][1] = {
    { 1.00000000000000000e+00f },
    { -5.95787353813648224e-02f },
    { -1.19455292820930481e-01f },
    { -8.74019265174865723e-02f },
    { -2.50461162067949772e-03f },
};

// CD [1][5] — output matrix
static const float DRIVE_CTRL_CD[1][5] = {
    { 1.58087193965911865e-01f, -2.97893676757812500e+01f, -5.97276458740234375e+01f, 4.37009582519531250e+01f, 1.24849164485931396e+00f },
};

// AC [5][5] = AD - BD*CD/DD — the CONDITIONED state matrix (use this one)
static const float DRIVE_CTRL_AC[5][5] = {
    { 9.07266199588775635e-01f, 1.74744205474853516e+01f, 3.50361938476562500e+01f, -2.56349487304687500e+01f, -7.32364237308502197e-01f },
    { 5.52496407181024551e-03f, -4.56225723028182983e-02f, -2.10280489921569824e+00f, 1.54134476184844971e+00f, 4.40043620765209198e-02f },
    { 1.10775465145707130e-02f, -2.10280489921569824e+00f, -3.28481912612915039e+00f, 3.23317503929138184e+00f, 9.06602069735527039e-02f },
    { 8.10511503368616104e-03f, -1.54134488105773926e+00f, -3.23317551612854004e+00f, 2.82539391517639160e+00f, 3.44721339643001556e-02f },
    { 2.32262231293134391e-04f, -4.41388040781021118e-02f, -9.09371674060821533e-02f, 3.45758162438869476e-02f, 1.63848429918289185e-01f },
};
