// mimo_controller_coeffs.h — GENERATED by controller_design_MIMO/synthesize_mimo_controller.py
// DO NOT EDIT BY HAND. Regenerate after bench calibration (mimo_system_model.md §9).
//
// NOT WIRED INTO THE FIRMWARE BUILD. This is the emitted artefact of the
// centralized 2x2 MIMO H-inf / Youla-H design (mimo_synthesis.md); firmware
// integration would be a separate, reviewed round.
//
// Controller (SCALED coordinates, single rate Ts = 2.0 ms / 500 Hz):
//     e_s   = DE^-1 * (ref - y)            [share, speed]
//     u_s   = C*x + D*e_s + x_int
//     x'    = A*x + B*e_s
//     x_int'= x_int + (Ts/2)*KI*(e_s + e_prev)      (exact 2x2 Tustin integrator)
//     u     = U0 + DU*u_s,  clamped to [U_MIN, U_MAX]
//     anti-windup: x_int += DU^-1*(u_sat - u), then x_int clamped to
//                  [XI_MIN, XI_MAX] = DU^-1*(U_MIN/U_MAX - U0)  (authority bound)
// ORDERING MATTERS: advance x_int FIRST and use the NEW value in u_s, exactly as
// the shipped SISO share_controller.h does — that makes the block the exact
// Tustin integrator KI*Ts(z+1)/(2(z-1)).
// The A matrix is in REAL MODAL (block-diagonal) form for float32 robustness.
//
// Design record: gamma (DGKF Riccati bisection) = 0.8977 — OPTIMISTIC for the
// 2x2 problem; the honest a-posteriori level is gamma = 1.6456 with
// ||Tzw||inf = 1.6457.  T(0) = I is enforced by the MIMO Youla-H DC correction
// and made structural by the exact 2x2 integrator split.
#pragma once

#define MIMO_CTRL_TS_US    2000      // controller update period, microseconds
#define MIMO_CTRL_NX       7         // stable-remainder states (plus 2 integrator states)
#define MIMO_CTRL_NY       2
#define MIMO_CTRL_NU       2

// stable remainder, discrete (Tustin @ Ts), real modal form
static const float MIMO_CTRL_A[MIMO_CTRL_NX][MIMO_CTRL_NX] = {
    { -9.866366201e-01f, -2.036582813e-17f, 4.169498322e-16f, 2.346077726e-17f, 2.276597341e-16f, -2.051421339e-16f, 6.830715172e-17f },
    { -5.041391902e-17f, 9.225008086e-01f, -1.298040903e-17f, 4.948835139e-18f, 3.049834954e-17f, 3.235502363e-17f, -1.497103888e-17f },
    { -2.233070889e-16f, 8.731428689e-18f, -8.591513033e-01f, 7.370961145e-02f, 4.892008341e-16f, 1.626684045e-16f, 5.865551396e-18f },
    { 1.212971116e-15f, 2.094642646e-17f, -7.370961145e-02f, -8.591513033e-01f, 2.062731226e-16f, -7.930030268e-18f, -1.238293187e-16f },
    { 3.892451464e-16f, -1.993007362e-17f, 1.962817715e-16f, -2.301064357e-17f, 6.205210346e-01f, -5.776369503e-16f, -8.325126477e-20f },
    { -6.694735670e-16f, 1.944628073e-17f, 2.322497508e-16f, 1.597963398e-17f, 6.229589889e-16f, -9.952338334e-02f, 2.397919334e-01f },
    { 1.678636591e-15f, -5.069789607e-17f, -1.351887048e-15f, 4.756509811e-17f, -1.476014625e-16f, -2.397919334e-01f, -9.952338334e-02f }
};
static const float MIMO_CTRL_B[MIMO_CTRL_NX][MIMO_CTRL_NU] = {
    { -1.720607600e-06f, -1.490097645e-03f },
    { 6.666076976e-06f, 1.158003293e-02f },
    { 4.448325856e-05f, 2.414371574e-03f },
    { 5.659275740e-06f, 3.257887317e-03f },
    { -3.646398669e-03f, 3.098966104e-04f },
    { -5.068946728e-06f, 2.430467708e-03f },
    { -7.360830206e-05f, -2.015456620e-02f }
};
static const float MIMO_CTRL_C[MIMO_CTRL_NY][MIMO_CTRL_NX] = {
    { 7.223757659e-02f, 3.039049921e+00f, 3.791742325e-01f, 6.244143007e-02f, 2.316518944e+00f, -2.014798401e+00f, -7.296024295e-01f },
    { -7.280169401e-01f, 4.903335020e+00f, 1.791068345e-02f, -1.684878259e-02f, -6.702064110e-03f, 5.435059840e-02f, -2.868090380e-03f }
};
static const float MIMO_CTRL_D[MIMO_CTRL_NY][MIMO_CTRL_NU] = {
    { -5.087086597e-03f, 1.223382621e-02f },
    { 1.282879005e-04f, 1.108555914e-01f }
};

// continuous integrator residue matrix (Tustin applied in code)
static const float MIMO_CTRL_KI[2][2] = {
    { 7.992467284e+00f, 1.645501029e-01f },
    { 7.784763615e-05f, 1.031862900e-01f }
};

// scaling: e_s = DE^-1 * e_phys ; u_phys = U0 + DU * u_s
static const float MIMO_CTRL_DE[2] = { 5.000000000e-02f, 5.000000000e-01f };   // [share, m/s]
static const float MIMO_CTRL_DU[2] = { 3.500000000e-01f, 2.000000000e+01f };   // [droop ratio, A]

// operating-point offsets the small-signal command is added to
static const float MIMO_CTRL_U0[2]    = { 5.000000000e-01f, 0.000000000e+00f };    // r0, i_m0
static const float MIMO_CTRL_U_MIN[2] = { 1.500000000e-01f, -2.000000000e+01f };
static const float MIMO_CTRL_U_MAX[2] = { 8.500000000e-01f, 2.000000000e+01f };

// integrator authority clamp (scaled): the integrator alone may never demand
// more than the actuator can deliver.  = DU^-1 (U_MIN - U0) and DU^-1 (U_MAX - U0).
static const float MIMO_CTRL_XI_MIN[2] = { -1.000000000e+00f, -1.000000000e+00f };
static const float MIMO_CTRL_XI_MAX[2] = { 1.000000000e+00f, 1.000000000e+00f };
// anti-windup back-calculation map (= DU^-1, diagonal), cond = 57.143
static const float MIMO_CTRL_DU_INV[2] = { 2.857142857e+00f, 5.000000000e-02f };

// measured-share prefilter 1/(tauf*s+1), tauf = 0.8 ms, discretized at Ts:
//   alphaFilt += (1 - A)*(alphaRaw - alphaFilt), A = exp(-Ts/tauf).
// It is PART OF THE DESIGN PLANT (mimo_system_model.md) — the loop is synthesized
// WITH this lag in it; do not remove it or retune it independently.
static const float MIMO_CTRL_MEAS_FILT_A = 8.208499862e-02f;
