// drive_controller_coeffs.h — GENERATED by
// controller_design_MIMO/synthesize_drive_siso.py.  DO NOT EDIT BY HAND.
// Regenerate after bench calibration (mimo_system_model.md §9), or after any change to
// the motor-current clamp (MOTOR_I_CMD_MAX in teensy_controller.ino must equal
// DRIVE_CTRL_I_MAX below — the anti-windup design depends on it).
//
// *** THIS IS THE FIRMWARE COPY. ***  Included by teensy_controller/drive_controller.h
// and compiled into the Teensy build when USE_YOULA_DRIVE_CONTROLLER is 1 (fw v10+).
// The study copy of the same coefficients is controller_design_MIMO/drive_siso_coeffs.h;
// both are written from one emitter in the generating script, so they cannot drift.
//
// SISO Youla-H velocity controller for the SC001 drive channel:
//   Gc(z) = R(z) + kI*Ts/2*(z+1)/(z-1),  e = v_ref - v [m/s]  ->  i_cmd [A]
// H-inf mixed sensitivity (gamma = 27.3683) + Youla-H DC rescale (T(0) = 1 exact),
// Tustin at Ts = 2.0 ms (500 Hz motor channel; VESC UART frame floor).
// R(z) is 2 DF2T biquad section(s); the integrator is kept separate to match the
// shipped share-controller header layout byte for byte.
//
// *** ANTI-WINDUP WARNING (differs from share_controller.h) ***
// The shipped share controller de-winds by back-calculating ONLY the integrator.  That
// is NOT sufficient here: the non-integral branch R has a low-frequency gain of
// 745.5 A/(m/s), so against the +-12 A clamp the biquad cascade alone saturates for
// |e| > 16.1 mm/s and its lag states wind up independently of the integrator.
// Measured on the 0->2 m/s step: integrator-only AW leaves a -0.48 m/s standing error
// and a 22.2 mm/s limit cycle.
// RE-CHECKED at the firmware's +-12 A clamp (2026-08-15 operator decision) on the
// re-identified plant (2026-08-16 calibration): e_sat scales with the clamp, so it must be
// re-answered on every clamp change.  Integrator-only AW is CLEAN for steps up to
// ~0.1 m/s (final error < 1e-4 m/s, no limit cycle) and breaks from ~0.2 m/s upward.
// It still FAILS the 0->2 m/s gate, so the Hanus form remains REQUIRED for this baseline.
// A correct implementation must condition the FULL
// controller state (Hanus self-conditioned form, used in the synthesis sims):
//     u_unsat = Cd x + Dd e ;  u = clamp(u_unsat) ;
//     x[k+1]  = (Ad - Bd*Cd/Dd) x + Bd*u/Dd            (Dd = 1.811060289e+00)
// i.e. this baseline costs a 5-state state-space realization on the Teensy, not a
// biquad cascade.  Recorded as a Phase-6 "Teensy implementation cost" datapoint.
// The realization is emitted below (DRIVE_CTRL_AD/BD/CD/DD/AC); replay reference vectors
// for a firmware implementation are in figures/drive_siso_replay.csv.
#pragma once

#define DRIVE_CTRL_TS_US   2000      // controller update period, microseconds
#define DRIVE_CTRL_NSOS    2
static const float DRIVE_CTRL_KI = 7.362548774e+01f;   // integrator gain (continuous kI, Tustin in code)
// constexpr (not plain const) so the firmware can static_assert these against its own
// MOTOR_I_CMD_MAX: a namespace-scope `const float` is NOT a constant expression in C++17, so
// the clamp-pairing guard would not compile against it.  Same float32 values either way.
static constexpr float DRIVE_CTRL_I_MIN = -1.200000000e+01f;   // A, motor current clamp (regen rail)
static constexpr float DRIVE_CTRL_I_MAX = 1.200000000e+01f;    // A, motor current clamp (drive rail)

// biquad sections: b0 b1 b2 a1 a2 (a0 = 1)
static const float DRIVE_CTRL_SOS[DRIVE_CTRL_NSOS][5] = {
    { 1.737434802e+00f, 2.478356094e+00f, 7.409212920e-01f, -1.554882692e+00f, 5.984034636e-01f },
    { 1.000000000e+00f, -1.985977210e+00f, 9.859784907e-01f, -1.997779971e+00f, 9.977801670e-01f },
};

// ── Hanus self-conditioned state-space realization ──────────────────────────
// This is the FULL controller Gc(z) = R(z) + kI*Ts/2*(z+1)/(z-1) realized as one
// 5-state discrete system, NOT a second copy of the biquads above.  DRIVE_CTRL_SOS is
// retained only for the unsaturated-equivalence test; the state-space form below is the
// one to implement, because it is the only one that de-winds correctly (see the
// anti-windup warning at the top of this file).
//
// Dimensions: n = 5 states, 1 input (velocity error e [m/s]), 1 output (i_cmd [A]).
//   AD is n x n, BD is n x 1, CD is 1 x n, DD is scalar, AC = AD - BD*CD/DD is n x n.
// All arrays are ROW-MAJOR.
//
// Update law, once per DRIVE_CTRL_TS_US, with e = v_ref - v_actual [m/s]:
//   u_unsat = sum_j CD[0][j]*x[j] + DD*e
//   u       = clamp(u_unsat, DRIVE_CTRL_I_MIN, DRIVE_CTRL_I_MAX)     -> i_cmd [A]
//   x_next[i] = sum_j AC[i][j]*x[j] + BD[i][0]*(u/DD)
//   x <- x_next
// Note the conditioning: the state update is driven by the CLAMPED u, not by e.  While
// unsaturated this is algebraically identical to x_next = AD x + BD e (that identity is
// what makes AD useful as a cross-check); once clamped it is what prevents windup.
// Replay vectors for both regimes: figures/drive_siso_replay.csv.
//
// NUMERICAL CAUTION — read before implementing.
// This realization contains an exact integrator (an AD eigenvalue at 1) and a second mode
// at ~0.9999, alongside CD entries of order 50.  Perturbations are INTEGRATED, not damped,
// so coefficient precision and arithmetic precision both matter more than usual here.
//   * COEFFICIENTS.  The values below are the exact float32 roundings of the synthesis
//     matrices, and figures/drive_siso_replay.csv was generated from these same rounded
//     values.  Header, replay vectors and a compiled constant table therefore hold
//     bit-identical coefficients.  (Emitting float64 text instead put the reference
//     vectors 1.7e-2 A away from anything this header can reproduce.)  AC is derived from
//     the rounded AD/BD/CD/DD and then rounded, so AC == AD - BD*CD/DD holds to
//     8.6e-07 — a float32 rounding of AC's largest entry, not a compounding error.
//   * ARITHMETIC.  The replay vectors assume a float64 (double) state recursion.  Running
//     the recursion in float32 costs a further ~1e-2 A on the saturated regen episode —
//     measured, not estimated (validate_drive_siso.py check 4).  The divergence appears
//     at rail RELEASE rather than by slow accumulation, so it is not bounded by shortening
//     the run.  A float32 state recursion is NOT adequate for this controller; use double
//     (or fixed point with equivalent headroom).
// Replay comparisons should be toleranced on the OUTPUT (a few mA of i_cmd), never on the
// individual states.
#define DRIVE_CTRL_NSTATES 5
static const float DRIVE_CTRL_DD = 1.81106030941009521e+00f;   // direct feedthrough, A per (m/s)

// AD [5][5] — unconditioned state matrix (cross-check only)
static const float DRIVE_CTRL_AD[5][5] = {
    { 1.00000000000000000e+00f, 0.00000000000000000e+00f, 0.00000000000000000e+00f, 0.00000000000000000e+00f, 0.00000000000000000e+00f },
    { 0.00000000000000000e+00f, 9.96174991130828857e-01f, 1.13332681357860565e-02f, -1.07865333557128906e-02f, 4.44174611402559094e-06f },
    { 0.00000000000000000e+00f, 1.13332681357860565e-02f, 9.29382920265197754e-01f, 1.28287851810455322e-01f, -4.02351361117325723e-05f },
    { 0.00000000000000000e+00f, 1.07865333557128906e-02f, -1.28287866711616516e-01f, 6.27197027206420898e-01f, 3.98931326344609261e-04f },
    { 0.00000000000000000e+00f, -4.44930628873407841e-06f, 4.03023259423207492e-05f, 3.99633165216073394e-04f, 9.99907732009887695e-01f },
};

// BD [5][1] — input matrix
static const float DRIVE_CTRL_BD[5][1] = {
    { 1.00000000000000000e+00f },
    { -7.05518051981925964e-02f },
    { 1.20681062340736389e-01f },
    { 9.56071913242340088e-02f },
    { -4.14862115576397628e-05f },
};

// CD [1][5] — output matrix
static const float DRIVE_CTRL_CD[1][5] = {
    { 1.47250980138778687e-01f, -3.52759017944335938e+01f, 6.03405342102050781e+01f, -4.78035964965820312e+01f, 2.07088682800531387e-02f },
};

// AC [5][5] = AD - BD*CD/DD — the CONDITIONED state matrix (use this one)
static const float DRIVE_CTRL_AC[5][5] = {
    { 9.18693482875823975e-01f, 1.94780387878417969e+01f, -3.33177947998046875e+01f, 2.63953647613525391e+01f, -1.14346649497747421e-02f },
    { 5.73632074519991875e-03f, -3.78035753965377808e-01f, 2.36196374893188477e+00f, -1.87302708625793457e+00f, 8.11178004369139671e-04f },
    { -9.81215480715036392e-03f, 2.36196351051330566e+00f, -3.09144377708435059e+00f, 3.31370854377746582e+00f, -1.42018264159560204e-03f },
    { -7.77348643168807030e-03f, 1.87302708625793457e+00f, -3.31370854377746582e+00f, 3.15078377723693848e+00f, -6.94304879289120436e-04f },
    { 3.37309870701574255e-06f, -8.12519341707229614e-04f, 1.42253132071346045e-03f, -6.95410475600510836e-04f, 9.99908208847045898e-01f },
};
