// share_controller_coeffs.h — GENERATED by controller_design/synthesize_controller.py
// DO NOT EDIT BY HAND. Regenerate after bench calibration (system_model.md §9).
//
// Youla-H robust power-share controller, Gc(z) = R(z) + kI*Ts/2*(z+1)/(z-1),
// discretized (Tustin) at Ts = 1.0 ms from the H-inf + Youla-H design
// (gamma = 0.6859, T(0) = 1 enforced; see controller_design/controller_synthesis.md).
// R(z) realized as 3 DF2T biquad section(s); the integrator is separate so the
// firmware can apply back-calculation anti-windup (share_controller.h).
#pragma once

#define SHARE_CTRL_TS_US   1000      // controller update period, microseconds
#define SHARE_CTRL_NSOS    3
static const float SHARE_CTRL_KI = 1.119296298e+02f;   // integrator gain (continuous kI, Tustin in code)
// measured-share prefilter 1/(tauf*s+1), tauf = 0.8 ms, discretized at Ts:
// alphaFilt += (1 - A)*(alphaRaw - alphaFilt), A = exp(-Ts/tauf). Part of the design
// plant (system_model.md 6d) — the loop is synthesized WITH this lag in it.
static const float SHARE_CTRL_MEAS_FILT_A = 2.865047969e-01f;

// biquad sections: b0 b1 b2 a1 a2 (a0 = 1)
static const float SHARE_CTRL_SOS[SHARE_CTRL_NSOS][5] = {
    { -2.678967935e-02f, -2.678967935e-02f, -0.000000000e+00f, -9.999960042e-01f, 0.000000000e+00f },
    { 1.000000000e+00f, -9.983889668e-01f, 0.000000000e+00f, -3.934269577e-01f, 0.000000000e+00f },
    { 1.000000000e+00f, -2.090419616e-02f, 0.000000000e+00f, 1.756703245e-01f, 0.000000000e+00f },
};
