#!/usr/bin/env python3
"""gen_drive_replay_header.py — regenerate controller_design_MIMO/drive_replay_vectors.h
from controller_design_MIMO/figures/drive_siso_replay.csv.

This is NOT a one-off. Re-run it any time synthesize_drive_siso.py regenerates the CSV
(new plant identification, new controller synthesis, new clamp, new seed) so the
generated test-vector header stays byte-for-byte in sync with the CSV it is derived from.

Usage (from repo root, MSYS2 UCRT64 or the ctrl-venv python):
    python tools/gen_drive_replay_header.py

Reads:  controller_design_MIMO/figures/drive_siso_replay.csv
Writes: controller_design_MIMO/drive_replay_vectors.h

The CSV has columns episode,k,e_in,u_out with two episodes, "regen" and "small" (see the
CSV's own header comment for what each represents). For each episode this script emits:
    #define DRIVE_REPLAY_<EPISODE>_N <count>
    static const float DRIVE_REPLAY_<EPISODE>_E[...] = { ... };   // e_in
    static const float DRIVE_REPLAY_<EPISODE>_U[...] = { ... };   // u_out
in upper-case episode order matching the CSV's own first-seen episode order, mirroring the
naming the drive-controller replay tests in test/test_main.cpp already consume
(DRIVE_REPLAY_REGEN_N/E/U, DRIVE_REPLAY_SMALL_N/E/U). Floats are re-emitted at 9 significant
digits (round-trips a float32 exactly) with an 'f' suffix, one value per line, matching the
existing header's formatting so diffs stay reviewable.
"""
import csv
import pathlib
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
CSV_PATH = REPO_ROOT / "controller_design_MIMO" / "figures" / "drive_siso_replay.csv"
OUT_PATH = REPO_ROOT / "controller_design_MIMO" / "drive_replay_vectors.h"


def fmt(x: float) -> str:
    return f"{x:.9e}f"


def main() -> int:
    episodes = {}   # name -> {"e": [...], "u": [...]}
    order = []
    with open(CSV_PATH, newline="") as f:
        reader = csv.DictReader(row for row in f if not row.lstrip().startswith("#"))
        for row in reader:
            ep = row["episode"]
            if ep not in episodes:
                episodes[ep] = {"e": [], "u": []}
                order.append(ep)
            episodes[ep]["e"].append(float(row["e_in"]))
            episodes[ep]["u"].append(float(row["u_out"]))

    if not order:
        print("ERROR: no data rows found in", CSV_PATH, file=sys.stderr)
        return 1

    lines = []
    lines.append("// drive_replay_vectors.h -- GENERATED from")
    lines.append("// controller_design_MIMO/figures/drive_siso_replay.csv (itself GENERATED by")
    lines.append("// synthesize_drive_siso.py) via tools/gen_drive_replay_header.py. DO NOT")
    lines.append("// HAND-EDIT -- rerun the converter if the CSV regenerates.")
    lines.append("// Mirrors the layout of controller_design/reference_vectors.h (share loop).")
    lines.append("#pragma once")
    lines.append("")

    for i, ep in enumerate(order):
        tag = ep.upper()
        e_vals = episodes[ep]["e"]
        u_vals = episodes[ep]["u"]
        n = len(e_vals)
        assert n == len(u_vals)
        lines.append(f"#define DRIVE_REPLAY_{tag}_N {n}")
        lines.append(f"static const float DRIVE_REPLAY_{tag}_E[DRIVE_REPLAY_{tag}_N] = {{")
        for v in e_vals:
            lines.append(f"    {fmt(v)},")
        lines.append("};")
        lines.append(f"static const float DRIVE_REPLAY_{tag}_U[DRIVE_REPLAY_{tag}_N] = {{")
        for v in u_vals:
            lines.append(f"    {fmt(v)},")
        lines.append("};")
        if i != len(order) - 1:
            lines.append("")

    OUT_PATH.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT_PATH} ({sum(len(episodes[e]['e']) for e in order)} total samples, "
          f"episodes: {', '.join(order)})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
